AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: CUP AWS Serverless Arch. for Email

Parameters:
  KMSKeyID:
    Type: String
    NoEcho: true
    Default: CHANGE_ME

  SNSTopicARN:
    Type: String

  DlsAccountId:
    Type: String
  
  StaticAssetsBasepath:
    Type: String

  AppsBasepath:
    Type: String
  
  FromEmailAddress:
    Type: String

  IeltsBundleCode:
    Type: String
  
  AttachLambdaFnToVPC: 
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  BFnSubnetIds:
    Type: CommaDelimitedList

  BFnSecurityGroupIds:
    Type: CommaDelimitedList
    
Conditions:
  IsVPCRequired: !Equals [true, !Ref AttachLambdaFnToVPC]

Resources:
  DeadLetterQueueForSubscription:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Join ["-", [!Ref AWS::StackName, deadLetterQueueForSubscription]]
      DelaySeconds: 0
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600 #14 days in seconds
        
  IELTSubscription:
    Type: "AWS::SNS::Subscription"
    DependsOn: [DeadLetterQueueForSubscription, QueueForFeedbackEmail]
    Properties:
      TopicArn: !Ref SNSTopicARN
      Endpoint: !GetAtt QueueForFeedbackEmail.Arn
      Protocol: "sqs"
      RawMessageDelivery: "true"
      FilterPolicy: 
        bundle-codes:
          - !Ref IeltsBundleCode
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueueForSubscription.Arn

  DeadLetterQueueForFeedbackEmail:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Join ["-", [!Ref AWS::StackName, deadLetterQueueForFeedbackEmail]]
      DelaySeconds: 0
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600 #14 days in seconds

  QueueForFeedbackEmail:
    Type: AWS::SQS::Queue
    DependsOn: [DeadLetterQueueForFeedbackEmail]
    Properties:
      QueueName: !Join ["-", [!Ref AWS::StackName, queueForFeedbackEmail]]
      VisibilityTimeout: 180
      ReceiveMessageWaitTimeSeconds: 20 #20 is the max value, for long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueueForFeedbackEmail.Arn
        maxReceiveCount: 5

  SendEmailFunction:
    Type: "AWS::Serverless::Function"
    DependsOn: [QueueForFeedbackEmail]
    Properties:
      FunctionName: !Join ["-", [!Ref AWS::StackName, SendEmailFunction]]
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: functions/send-email
      Description: Function Triggered on new entry in QueueForFeedbackEmail
      MemorySize: 512
      Timeout: 90
      Role: !GetAtt SendEmailRole.Arn
      Environment:
        Variables:
          EMAIL_Q_URL: !GetAtt QueueForFeedbackEmail.Arn
          ACCOUNT_ID: !Ref DlsAccountId
          STATIC_ASSETS_BASEPATH: !Ref StaticAssetsBasepath
          APPS_BASEPATH: !Ref AppsBasepath
          EMAIL_ADDRESS_GENERAL: !Ref FromEmailAddress
          IELTS_BUNDLE_CODE: !Ref IeltsBundleCode
      KmsKeyArn: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSKeyID}"
      VpcConfig:
        !If
          - IsVPCRequired
          -
            SubnetIds: !Ref BFnSubnetIds
            SecurityGroupIds: !Ref BFnSecurityGroupIds
          - !Ref 'AWS::NoValue'
      Events:
        QueueForFeedbackEmailEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt QueueForFeedbackEmail.Arn
            BatchSize: 10

  SendEmailRole:
    Type: AWS::IAM::Role
    DependsOn: [QueueForFeedbackEmail]
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - PolicyName: SendMail
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ses:SendTemplatedEmail"
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource:
                  - "*"
        - PolicyName: DeleteMessageFromQueue
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ChangeMessageVisibility
                  - sqs:ChangeMessageVisibilityBatch
                  - sqs:DeleteMessage
                  - sqs:DeleteMessageBatch
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                Resource:
                  - !GetAtt QueueForFeedbackEmail.Arn
        - PolicyName: KMSAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kms:DescribeKey
                  - kms:GenerateDataKey
                  - kms:Decrypt
                  - kms:Encrypt
                Resource:
                  - !Sub "arn:aws:kms:*:*:key/${KMSKeyID}"

Outputs:
  QueueForFeedbackEmail:
    Description: "Queue for applying filter on SNS"
    Value: !Ref QueueForFeedbackEmail
  SendEmailFunction:
    Description: "Triggered on new entry in QueueForFeedbackEmail Lambda Function ARN"
    Value: !GetAtt SendEmailFunction.Arn
  IELTSubscription:
    Description: "Triggered on new entry in QueueForFeedbackEmail Lambda Function ARN"
    Value: !GetAtt SendEmailFunction.Arn
  SendEmailRole:
    Description: "Role for SendEmail Lambda Execution ARN"
    Value: !GetAtt SendEmailRole.Arn